#include "harmonyutils.h"

#include "harmonyconfigurations.h"
#include "harmonylogcategories.h"
#include "harmonyqtversion.h"
#include "ohosconstants.h"
#include "ohostr.h"
#include "ohprojectecreator/ohprojectecreator.h"
#include <cmakeprojectmanager/cmakeprojectconstants.h>
#include <coreplugin/icontext.h>
#include "harmonydevice.h"
#include "hdcsocketclient.h"

#include <projectexplorer/buildconfiguration.h>
#include <projectexplorer/buildsystem.h>
#include <projectexplorer/devicesupport/devicekitaspects.h>
#include <projectexplorer/devicesupport/idevice.h>
#include <projectexplorer/kit.h>
#include <projectexplorer/project.h>
#include <projectexplorer/projectnodes.h>
#include <projectexplorer/target.h>

#include <qtsupport/qtkitaspect.h>
#include <utils/qtcprocess.h>
#include <QDir>
#include <QDirIterator>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>

#include <algorithm>

using namespace ProjectExplorer;
using namespace Utils;
namespace Ohos::Internal {
const char HarmonyAppJson5Name[] = "app.json5";
const char HarmonyDeviceSn[] = "HarmonyDeviceSerialNumber";
const char HarmonyDeviceAbis[] = "HarmonyDeviceAbis";
const char ApiLevelKey[] = "HarmonyVersion.ApiLevel";
const char qtcSignature[] = "This file is generated by QtCreator to be read by "
                            "harmonydeployqt and should not be modified by hand.";

bool openDevEcoProject(const QString &path)
{
    Utils::FilePath devecostudioExe = HarmonyConfig::devecostudioExeLocation();
    if (!devecostudioExe.isExecutableFile())
        return false;
    const Utils::CommandLine command{devecostudioExe, {path}};
    return Utils::Process::startDetached(command);
}

QStringList applicationAbis(const ProjectExplorer::Kit *k)
{
    const auto *qt = dynamic_cast<HarmonyQtVersion *>(QtSupport::QtKitAspect::qtVersion(k));
    return qt ? qt->ohosAbis() : QStringList();
}

QStringList hdcSelector(const QString &serialNumber)
{
    // if (serialNumber.startsWith(QLatin1String("????")))
    //     return {"-d"};
    return {"-t", serialNumber};
}

bool harmonyHdcShellPreferCli()
{
    return HdcSocketClient::preferCliFromEnvironment();
}

QString harmonyEffectiveDeviceSerial(const BuildConfiguration *bc)
{
    if (!bc)
        return {};
    QString serial = deviceSerialNumber(bc);
    if (!serial.isEmpty())
        return serial.trimmed();
    if (Kit *kit = bc->kit()) {
        if (const IDevice::ConstPtr dev = RunDeviceKitAspect::device(kit))
            serial = HarmonyDevice::harmonyDeviceInfoFromDevice(dev).serialNumber;
    }
    return serial.trimmed();
}

static const ProjectNode *currentProjectNode(const BuildConfiguration *bc)
{
    return bc->project()->findNodeForBuildKey(bc->activeBuildKey());
}

QString packageName(const ProjectExplorer::BuildConfiguration *bc)
{
    QString packageName;
    const FilePath harmonyBuildDir = harmonyBuildDirectory(bc);
    const Result<QByteArray> appJsonContents = harmonyBuildDir.pathAppended("AppScope/app.json5")
                                                  .fileContents();
    if (appJsonContents) {
        QJsonObject rootJson = QJsonDocument::fromJson(*appJsonContents).object();
        auto appObject = rootJson.value("app").toObject();
        packageName = appObject.value("bundleName").toString();
    }
    return packageName;
}

static QString abilityFromModuleJsonObject(const QJsonObject &moduleObject)
{
    const QJsonArray abilities = moduleObject.value(QStringLiteral("abilities")).toArray();
    if (abilities.isEmpty())
        return {};

    QString firstName;
    QString exportedName;
    for (const QJsonValue &v : abilities) {
        const QJsonObject ab = v.toObject();
        const QString n = ab.value(QStringLiteral("name")).toString();
        if (n.isEmpty())
            continue;
        if (firstName.isEmpty())
            firstName = n;
        if (ab.value(QStringLiteral("exported")).toBool())
            exportedName = n;
    }
    if (!exportedName.isEmpty())
        return exportedName;
    return firstName;
}

static void collectAbilityFromModuleJson5(const FilePath &jsonPath,
                                          QString *entryAbility,
                                          QString *anyAbility)
{
    if (!jsonPath.isReadableFile())
        return;

    const Result<QByteArray> raw = jsonPath.fileContents();
    if (!raw)
        return;

    QJsonParseError err{};
    const QJsonDocument doc = QJsonDocument::fromJson(*raw, &err);
    if (err.error != QJsonParseError::NoError || !doc.isObject())
        return;

    const QJsonObject moduleObject = doc.object().value(QStringLiteral("module")).toObject();
    if (moduleObject.isEmpty())
        return;

    const QString ability = abilityFromModuleJsonObject(moduleObject);
    if (ability.isEmpty())
        return;

    if (moduleObject.value(QStringLiteral("type")).toString() == QStringLiteral("entry")) {
        if (entryAbility->isEmpty())
            *entryAbility = ability;
    } else if (anyAbility->isEmpty()) {
        *anyAbility = ability;
    }
}

QString defaultHarmonyAbilityName(const BuildConfiguration *bc)
{
    const FilePath root = harmonyBuildDirectory(bc);
    if (root.isEmpty() || !root.isReadableDir())
        return {};

    QString entryAbility;
    QString anyAbility;

    collectAbilityFromModuleJson5(root.pathAppended(QStringLiteral("entry/src/main/module.json5")),
                                &entryAbility,
                                &anyAbility);

    if (root.isReadableDir()) {
        const FilePaths children = root.dirEntries(QDir::Dirs | QDir::NoDotAndDotDot);
        for (const FilePath &ch : children) {
            const QString name = ch.fileName();
            if (name == QStringLiteral("AppScope") || name == QStringLiteral("hvigor")
                || name == QStringLiteral("oh_modules") || name.startsWith(QLatin1Char('.')))
                continue;
            collectAbilityFromModuleJson5(ch.pathAppended(QStringLiteral("src/main/module.json5")),
                                        &entryAbility,
                                        &anyAbility);
        }
    }

    if (!entryAbility.isEmpty())
        return entryAbility;
    return anyAbility;
}

Utils::FilePath harmonyBuildDirectory(const ProjectExplorer::BuildConfiguration *bc)
{
    QString suffix;
    const ProjectExplorer::Project *project = bc->project();
    if (project->extraData(Ohos::Constants::HarmonyBuildTargetDirSupport).toBool()
        && project->extraData(Ohos::Constants::UseHarmonyBuildTargetDir).toBool())
        suffix = QString("-%1").arg(bc->activeBuildKey());

    return buildDirectory(bc) / (Constants::HARMONY_BUILD_DIRECTORY + suffix);
}

Utils::FilePath buildDirectory(const ProjectExplorer::BuildConfiguration *bc)
{
    const QString buildKey = bc->activeBuildKey();

    /* ** 根据设置文件路径获取目标构建目录 */
    FilePath buildDir;
    const ProjectNode *node = bc->project()->findNodeForBuildKey(buildKey);
    if (node) {
        const QString settingsFile = node->data(Constants::HarmonyDeploySettingsFile).toString();
        buildDir = FilePath::fromUserInput(settingsFile).parentDir();
    }

    if (!buildDir.isEmpty())
        return buildDir;

    /* ** 否则回退到目标工作目录 */
    buildDir = bc->buildDirectory();
    return buildDir;
}

QString buildKeyForCMakeExtraData(const BuildConfiguration *bc)
{
    if (!bc)
        return {};
    const QString buildKey = bc->activeBuildKey();
    if (buildKey != QString::fromLatin1(Constants::HARMONY_DEFAULT_RUN_BUILD_KEY))
        return buildKey;
    const BuildSystem *bs = bc->buildSystem();
    const Project *proj = bc->project();
    if (!bs || !proj)
        return buildKey;
    for (const BuildTargetInfo &ti : bs->applicationTargets()) {
        if (ti.buildKey.isEmpty())
            continue;
        if (proj->findNodeForBuildKey(ti.buildKey))
            return ti.buildKey;
    }
    return buildKey;
}

bool isQt5CmakeProject(const ProjectExplorer::Target *target)
{
    const QtSupport::QtVersion *qt = QtSupport::QtKitAspect::qtVersion(target->kit());
    const bool isQt5 = qt && qt->qtVersion() < QVersionNumber(6, 0, 0);
    const Core::Context cmakeCtx(CMakeProjectManager::Constants::CMAKE_PROJECT_ID);
    const bool isCmakeProject = (target->project()->projectContext() == cmakeCtx);
    return isQt5 && isCmakeProject;
}

QString deviceSerialNumber(const ProjectExplorer::BuildConfiguration *bc)
{
    return bc->extraData(HarmonyDeviceSn).toString();
}

void setDeviceSerialNumber(ProjectExplorer::BuildConfiguration *bc, const QString &deviceSerialNumber)
{
    qCDebug(harmonyDeviceLog) << "Target device serial changed:"
                               << bc->target()->displayName() << deviceSerialNumber;
    bc->setExtraData(HarmonyDeviceSn, deviceSerialNumber);
}
static QString preferredAbi(const QStringList &appAbis, const BuildConfiguration *bc)
{
    const auto deviceAbis = bc->extraData(HarmonyDeviceAbis).toStringList();

    return Utils::findOrDefault(deviceAbis,[appAbis](const auto &abi) { return appAbis.contains(abi); });
}
QString hapDevicePreferredAbi(const ProjectExplorer::BuildConfiguration *bc)
{
    const FilePath libsPath = harmonyBuildDirectory(bc).pathAppended("entry/libs");
    if (!libsPath.exists()) {
        if (const ProjectNode *node = currentProjectNode(bc)) {
            const QString abi = preferredAbi(
                node->data(Ohos::Constants::HarmonyAbis).toStringList(), bc);
            if (abi.isEmpty())
                return node->data(Ohos::Constants::OHOS_ARCH).toString();
        }
    }
    QStringList apkAbis;
    const FilePaths libsPaths = libsPath.dirEntries(QDir::Dirs | QDir::NoDotAndDotDot);
    for (const FilePath &abiDir : libsPaths) {
        if (!abiDir.dirEntries({{"*.so"}, QDir::Files | QDir::NoDotAndDotDot}).isEmpty())
            apkAbis << abiDir.fileName();
    }
    return preferredAbi(apkAbis, bc);
}

void setDeviceAbis(ProjectExplorer::BuildConfiguration *bc, const QStringList &deviceAbis)
{
    bc->setExtraData(HarmonyDeviceAbis, deviceAbis);
}

int deviceApiLevel(const ProjectExplorer::BuildConfiguration *bc)
{
    return bc->extraData(ApiLevelKey).toInt();
}

void setDeviceApiLevel(ProjectExplorer::BuildConfiguration *bc, int level)
{
    qCDebug(harmonyDeviceLog) << "Target device API level changed:"
                               << bc->target()->displayName() << level;
    bc->setExtraData(ApiLevelKey, level);
}

FilePath appJson5Path(const ProjectExplorer::BuildConfiguration *bc)
{
    QVariant manifest = bc->extraData(HarmonyAppJson5Name);
    if (manifest.isValid())
        return manifest.value<FilePath>();
    return harmonyBuildDirectory(bc).pathAppended(HarmonyAppJson5Name);
}

void setAppJson5Path(ProjectExplorer::BuildConfiguration *bc, const Utils::FilePath &path)
{
    bc->setExtraData(HarmonyAppJson5Name, QVariant::fromValue(path));
}
static int parseMinSdk(const FilePath &appJson5Path)
{
    const Result<QByteArray> appJsonContents = appJson5Path.fileContents();
    if (!appJsonContents) {
        qCWarning(harmonyDeployLog) << "Failed to read" << appJson5Path;
        return 0;
    }
    QJsonObject rootJson = QJsonDocument::fromJson(*appJsonContents).object();
    auto productsArray = rootJson.value("products").toArray();
    int minSdkVersion = OhProjecteCreator::latestApiLevel();
    for (const auto &productValue : std::as_const(productsArray)) {
        auto productObject = productValue.toObject();
        QString compatibleSdkVersion = productObject.value("compatibleSdkVersion").toString();
        minSdkVersion = qMin(minSdkVersion, OhProjecteCreator::apiLevelForVersion(compatibleSdkVersion));
    }
    return minSdkVersion;
}

int minimumSDK(const ProjectExplorer::BuildConfiguration *bc)
{
    const auto buildProfile = harmonyBuildDirectory(bc).pathAppended("build-profile.json5");
    if (!buildProfile.exists())
        return minimumSDK(bc->kit());

    const int minSdkVersion = parseMinSdk(buildProfile);
    if (minSdkVersion == 0)
        return defaultMinimumSDK(QtSupport::QtKitAspect::qtVersion(bc->kit()));
    return minSdkVersion;
}

int minimumSDK(const ProjectExplorer::Kit *kit)
{
    int minSdkVersion = -1;
    QtSupport::QtVersion *version = QtSupport::QtKitAspect::qtVersion(kit);
    if (version && version->targetDeviceTypes().contains(Constants::HARMONY_DEVICE_TYPE)) {
        auto harmonyQt = dynamic_cast<const HarmonyQtVersion *>(version);

        if (harmonyQt)
            minSdkVersion = harmonyQt->supportOhVersion().majorVersion();
    }
    if (minSdkVersion == 0)
        return defaultMinimumSDK(version);
    return minSdkVersion;
}

int defaultMinimumSDK(const QtSupport::QtVersion *qtVersion)
{
    auto harmonyQt = dynamic_cast<const HarmonyQtVersion *>(qtVersion);
    if (harmonyQt)
        return harmonyQt->supportOhVersion().majorVersion();
    return OhProjecteCreator::defaultApiLevel();
}

namespace {

const QString kOutputsRelative = QStringLiteral("build/default/outputs/default");

FilePath moduleRootFromBuildProfileEntry(const FilePath &ohProRoot, const QJsonObject &moduleObject)
{
    const QString srcPath = moduleObject.value(QStringLiteral("srcPath")).toString().trimmed();
    if (!srcPath.isEmpty())
        return ohProRoot.resolvePath(srcPath);
    const QString name = moduleObject.value(QStringLiteral("name")).toString();
    if (!name.isEmpty())
        return ohProRoot.pathAppended(name);
    return {};
}

FilePath pickHapInOutputDir(const FilePath &outputDir, const QString &moduleName)
{
    if (!outputDir.isReadableDir())
        return {};

    const QStringList exactCandidates{
        moduleName + QStringLiteral("-default-signed.hap"),
        moduleName + QStringLiteral("-default-debug-signed.hap"),
        moduleName + QStringLiteral("-signed.hap"),
    };
    for (const QString &fn : exactCandidates) {
        const FilePath p = outputDir.pathAppended(fn);
        if (p.isReadableFile())
            return p;
    }

    FilePaths haps = outputDir.dirEntries({{QStringLiteral("*.hap")}, QDir::Files});
    if (haps.isEmpty())
        return {};
    std::sort(haps.begin(), haps.end(), [](const FilePath &a, const FilePath &b) {
        return a.lastModified() > b.lastModified();
    });
    return haps.front();
}

static void appendDiagnostic(QStringList *diagnostic, const QString &msg)
{
    if (diagnostic)
        diagnostic->append(msg);
}

static FilePath tryOneModule(const FilePath &ohProRoot,
                             const QJsonObject &mo,
                             const QString &phase,
                             QStringList *diagnostic)
{
    const QString moduleName = mo.value(QStringLiteral("name")).toString();
    const FilePath modRoot = moduleRootFromBuildProfileEntry(ohProRoot, mo);
    if (moduleName.isEmpty() || modRoot.isEmpty()) {
        appendDiagnostic(diagnostic, QStringLiteral("[%1] skip (missing module name or path).").arg(phase));
        return {};
    }
    const FilePath outputDir = modRoot.pathAppended(kOutputsRelative);
    appendDiagnostic(diagnostic,
                     QStringLiteral("[%1] module \"%2\" → %3")
                         .arg(phase, moduleName, outputDir.toUserOutput()));
    return pickHapInOutputDir(outputDir, moduleName);
}

FilePath resolveFromBuildProfileModules(const FilePath &ohProRoot, QStringList *diagnostic)
{
    const FilePath profilePath = ohProRoot.pathAppended(QStringLiteral("build-profile.json5"));
    if (!profilePath.isReadableFile()) {
        appendDiagnostic(diagnostic, QStringLiteral("No readable build-profile.json5 — using entry + scan fallbacks."));
        return {};
    }

    const Result<QByteArray> content = profilePath.fileContents();
    if (!content) {
        appendDiagnostic(diagnostic, QStringLiteral("Could not read build-profile.json5."));
        return {};
    }

    QJsonParseError parseError{};
    const QJsonDocument doc = QJsonDocument::fromJson(*content, &parseError);
    if (parseError.error != QJsonParseError::NoError || !doc.isObject()) {
        appendDiagnostic(diagnostic, QStringLiteral("build-profile.json5: JSON error: %1")
                                         .arg(parseError.errorString()));
        return {};
    }

    const QJsonArray modules = doc.object().value(QStringLiteral("modules")).toArray();
    if (modules.isEmpty()) {
        appendDiagnostic(diagnostic, QStringLiteral("build-profile.json5: empty modules[] — using entry fallbacks."));
        return {};
    }

    for (const QJsonValue &mv : modules) {
        const QJsonObject mo = mv.toObject();
        if (mo.value(QStringLiteral("type")).toString() != QStringLiteral("entry"))
            continue;
        const FilePath found = tryOneModule(ohProRoot, mo, QStringLiteral("entry-type"), diagnostic);
        if (!found.isEmpty())
            return found;
    }

    for (const QJsonValue &mv : modules) {
        const QJsonObject mo = mv.toObject();
        if (mo.value(QStringLiteral("type")).toString() == QStringLiteral("entry"))
            continue;
        const FilePath found = tryOneModule(ohProRoot, mo, QStringLiteral("other-module"), diagnostic);
        if (!found.isEmpty())
            return found;
    }

    return {};
}

FilePath legacyEntryHap(const FilePath &ohProRoot, QStringList *diagnostic)
{
    const FilePath defaultPath = ohProRoot.pathAppended(
        QStringLiteral("entry/build/default/outputs/default/entry-default-signed.hap"));
    if (diagnostic)
        diagnostic->append(QStringLiteral("Legacy path: %1").arg(defaultPath.toUserOutput()));
    if (defaultPath.isReadableFile())
        return defaultPath;

    const FilePath outputDir = ohProRoot.pathAppended(QStringLiteral("entry/build/default/outputs/default"));
    return pickHapInOutputDir(outputDir, QStringLiteral("entry"));
}

FilePath newestHapRecursive(const FilePath &ohProRoot, QStringList *diagnostic)
{
    QDirIterator it(ohProRoot.toUserOutput(),
                    {QStringLiteral("*.hap")},
                    QDir::Files,
                    QDirIterator::Subdirectories);
    FilePath best;
    QDateTime bestTime;
    int n = 0;
    while (it.hasNext()) {
        const FilePath candidate = FilePath::fromString(it.next());
        if (!candidate.isReadableFile())
            continue;
        ++n;
        const QDateTime t = candidate.lastModified();
        if (!bestTime.isValid() || t > bestTime) {
            bestTime = t;
            best = candidate;
        }
    }
    if (diagnostic) {
        diagnostic->append(QStringLiteral("Recursive *.hap: %1 file(s); newest: %2")
                                 .arg(QString::number(n),
                                      best.isEmpty() ? QStringLiteral("(none)") : best.toUserOutput()));
    }
    return best;
}

} // namespace

FilePath findBuiltHapPackage(const FilePath &ohProRoot, QString *diagnosticOut)
{
    if (!ohProRoot.isReadableDir()) {
        if (diagnosticOut)
            *diagnosticOut = QStringLiteral("Not a readable directory: ") + ohProRoot.toUserOutput();
        return {};
    }

    QStringList lines;
    FilePath found = resolveFromBuildProfileModules(ohProRoot, &lines);
    if (found.isEmpty())
        found = legacyEntryHap(ohProRoot, &lines);
    if (found.isEmpty())
        found = newestHapRecursive(ohProRoot, &lines);

    if (diagnosticOut)
        *diagnosticOut = lines.join(QLatin1Char('\n'));

    return found;
}

QStringList parseOhModuleDeviceTypesLine(const QString &line)
{
    QStringList out;
    for (const QString &part : line.split(QLatin1Char(','), Qt::SkipEmptyParts)) {
        const QString t = part.trimmed();
        if (!t.isEmpty())
            out.append(t);
    }
    return out;
}

QString joinOhModuleDeviceTypesLine(const QStringList &types)
{
    return types.join(QStringLiteral(", "));
}

QStringList ohModuleDeviceTypePresetIds()
{
    return {QStringLiteral("phone"), QStringLiteral("tablet"), QStringLiteral("2in1"),
            QStringLiteral("wearable"), QStringLiteral("tv"), QStringLiteral("car")};
}

QString harmonyNameForApiLevel(int x)
{
    switch (x) {
    case 12:
        return QLatin1String("HarmonyOS 5.0.0");
    case 13:
        return QLatin1String("HarmonyOS 5.0.1");
    case 14:
        return QLatin1String("HarmonyOS 5.0.2");
    case 15:
        return QLatin1String("HarmonyOS 5.0.3");
    case 16:
        return QLatin1String("HarmonyOS 5.0.4");
    case 17:
        return QLatin1String("HarmonyOS 5.0.5");
    case 18:
        return QLatin1String("HarmonyOS 5.1.0");
    case 19:
        return QLatin1String("HarmonyOS 5.1.1");
    case 20:
        return QLatin1String("HarmonyOS 6.0.0");
    default:
        return Tr::tr("Unknown HarmonyOS version. API Level: %1").arg(x);
    }
}

}
