#include "harmonyutils.h"

#include "harmonyconfigurations.h"
#include "harmonylogcategories.h"
#include "harmonyqtversion.h"
#include "ohosconstants.h"
#include "ohprojectecreator/ohprojectecreator.h"
#include <cmakeprojectmanager/cmakeprojectconstants.h>
#include <coreplugin/icontext.h>
#include "harmonydevice.h"

#include <projectexplorer/buildconfiguration.h>
#include <projectexplorer/buildsystem.h>
#include <projectexplorer/devicesupport/devicekitaspects.h>
#include <projectexplorer/devicesupport/idevice.h>
#include <projectexplorer/kit.h>
#include <projectexplorer/project.h>
#include <projectexplorer/projectnodes.h>
#include <projectexplorer/runconfiguration.h>
#include <projectexplorer/target.h>

#include <qtsupport/qtkitaspect.h>
#include <utils/id.h>
#include <utils/qtcprocess.h>
#include <utils/store.h>
#include <QDir>
#include <QRegularExpression>
#include <chrono>
#include <QDirIterator>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>

#include <algorithm>

using namespace ProjectExplorer;
using namespace Utils;
namespace Ohos::Internal {
const char HarmonyAppJson5Name[] = "app.json5";
const char HarmonyDeviceSn[] = "HarmonyDeviceSerialNumber";
const char HarmonyDeviceAbis[] = "HarmonyDeviceAbis";
const char ApiLevelKey[] = "HarmonyVersion.ApiLevel";
const char qtcSignature[] = "This file is generated by QtCreator to be read by "
                            "harmonydeployqt and should not be modified by hand.";

bool openDevEcoProject(const QString &path)
{
    Utils::FilePath devecostudioExe = HarmonyConfig::devecostudioExeLocation();
    if (!devecostudioExe.isExecutableFile())
        return false;
    const Utils::CommandLine command{devecostudioExe, {path}};
    return Utils::Process::startDetached(command);
}

QStringList applicationAbis(const ProjectExplorer::Kit *k)
{
    const auto *qt = dynamic_cast<HarmonyQtVersion *>(QtSupport::QtKitAspect::qtVersion(k));
    return qt ? qt->ohosAbis() : QStringList();
}

QStringList hdcSelector(const QString &serialNumber)
{
    // if (serialNumber.startsWith(QLatin1String("????")))
    //     return {"-d"};
    return {"-t", serialNumber};
}

QString harmonyDebuggerBundleName(const BuildConfiguration *bc)
{
    if (!bc)
        return {};
    RunConfiguration *rc = bc->activeRunConfiguration();
    const Store sd = rc ? rc->settingsData().value(Id(Constants::HARMONY_RUN_BUNDLE_OVERRIDE)) : Store{};
    const QString o = sd.value(Key("Harmony.Run.BundleNameOverrideKey")).toString().trimmed();
    if (!o.isEmpty())
        return o;
    return packageName(bc);
}

QString harmonyDebuggerAbilityName(const BuildConfiguration *bc)
{
    if (!bc)
        return QStringLiteral("EntryAbility");
    RunConfiguration *rc = bc->activeRunConfiguration();
    const Store sd = rc ? rc->settingsData().value(Id(Constants::HARMONY_RUN_ABILITY_OVERRIDE)) : Store{};
    const QString o = sd.value(Key("Harmony.Run.AbilityNameOverrideKey")).toString().trimmed();
    if (!o.isEmpty())
        return o;
    QString a = defaultHarmonyAbilityName(bc);
    if (a.isEmpty())
        a = QStringLiteral("EntryAbility");
    return a;
}

QString harmonyEffectiveDeviceSerial(const BuildConfiguration *bc)
{
    if (!bc)
        return {};
    QString serial = deviceSerialNumber(bc);
    if (!serial.isEmpty())
        return serial.trimmed();
    if (Kit *kit = bc->kit()) {
        if (const IDevice::ConstPtr dev = RunDeviceKitAspect::device(kit))
            serial = HarmonyDevice::harmonyDeviceInfoFromDevice(dev).serialNumber;
    }
    return serial.trimmed();
}

namespace {
static QString runHdcShellOutput(const FilePath &hdc, const QString &serial, const QStringList &shellArgs)
{
    if (!hdc.isExecutableFile() || serial.isEmpty())
        return {};
    CommandLine cmd{hdc, hdcSelector(serial)};
    cmd.addArg(QStringLiteral("shell"));
    cmd.addArgs(shellArgs);
    Process p;
    p.setCommand(cmd);
    p.setWorkingDirectory(hdc.parentDir());
    p.runBlocking(std::chrono::seconds(30));
    return QString::fromUtf8(p.allRawOutput());
}

static qint64 parsePidFromKeyValueDump(const QString &out)
{
    // Keep this strict: avoid matching appId/uid/gid-like fields from bm dump JSON.
    static const QRegularExpression re(
        QStringLiteral(R"((?:^|[{\s,"'])(?:pid|PID)(?:\s*["'])?\s*[:：=]\s*(\d+))"));
    const QRegularExpressionMatch m = re.match(out);
    if (m.hasMatch())
        return m.captured(1).toLongLong();
    return -1;
}

static QList<qint64> parsePidListFromPidof(const QString &out)
{
    const QStringList tok = out.simplified().split(' ', Qt::SkipEmptyParts);
    QList<qint64> pids;
    for (const QString &t : tok) {
        bool ok = false;
        const qint64 v = t.toLongLong(&ok);
        if (ok && v > 0)
            pids.append(v);
    }
    return pids;
}

static qint64 pickBestPidFromPsForBundle(const QString &psOut,
                                         const QString &bundle,
                                         const QList<qint64> &candidates)
{
    if (bundle.isEmpty() || candidates.isEmpty())
        return -1;
    struct Candidate
    {
        qint64 pid = -1;
        int rank = -1; // higher is better
    };
    Candidate best;
    const QStringList lines = psOut.split('\n', Qt::SkipEmptyParts);
    for (const QString &line : lines) {
        const QString simp = line.simplified();
        const QStringList tok = simp.split(' ', Qt::SkipEmptyParts);
        if (tok.isEmpty())
            continue;
        qint64 linePid = -1;
        for (const QString &t : tok) {
            bool ok = false;
            const qint64 v = t.toLongLong(&ok);
            if (ok && v > 0) {
                linePid = v;
                break;
            }
        }
        if (linePid <= 0 || !candidates.contains(linePid))
            continue;
        const QString cmdToken = tok.constLast();
        int rank = 1;
        if (cmdToken.compare(bundle, Qt::CaseInsensitive) == 0)
            rank = 3; // main process
        else if (cmdToken.startsWith(bundle + QLatin1Char(':'), Qt::CaseInsensitive))
            rank = 2; // sub process
        if (rank > best.rank) {
            best.rank = rank;
            best.pid = linePid;
        }
    }
    return best.pid;
}

static qint64 parsePidFromPs(const QString &out, const QString &bundle)
{
    struct Candidate
    {
        qint64 pid = -1;
        int rank = -1; // higher is better
    };

    Candidate best;
    const QStringList lines = out.split('\n', Qt::SkipEmptyParts);
    for (const QString &line : lines) {
        if (!line.contains(bundle, Qt::CaseInsensitive))
            continue;
        const QString simp = line.simplified();
        const QStringList tok = simp.split(' ', Qt::SkipEmptyParts);
        if (tok.isEmpty())
            continue;

        const QString cmdToken = tok.constLast();
        int rank = -1;
        if (cmdToken.compare(bundle, Qt::CaseInsensitive) == 0) {
            // Exact package process name: best candidate.
            rank = 3;
        } else if (cmdToken.startsWith(bundle + QLatin1Char(':'), Qt::CaseInsensitive)) {
            // App sub-process (e.g. bundle:render / bundle:service): second best.
            rank = 2;
        } else if (line.contains(bundle, Qt::CaseInsensitive)) {
            // Weak fallback for unexpected ps layouts.
            rank = 1;
        }

        // Typical `ps -A` format on OHOS is: PID TTY TIME CMD.
        bool okFirst = false;
        const qint64 first = tok.constFirst().toLongLong(&okFirst);
        if (okFirst && first > 0) {
            if (rank > best.rank) {
                best.pid = first;
                best.rank = rank;
            }
            continue;
        }

        // Fallback for unexpected formats where PID is not the first token.
        for (const QString &t : tok) {
            bool ok = false;
            const qint64 v = t.toLongLong(&ok);
            if (ok && v > 0) {
                if (rank > best.rank) {
                    best.pid = v;
                    best.rank = rank;
                }
                break;
            }
        }
    }
    return best.pid;
}

static qint64 parsePidFromAaProcessDump(const QString &out, const QString &bundle)
{
    // Accept both legacy "pid #12345" and newer key/value variants like "pid: 12345".
    static const QRegularExpression pidRe(
        QStringLiteral(R"((?:^|[\s,;])pid(?:\s*#|\s*[:=]\s*|\s+)(\d+))"),
        QRegularExpression::CaseInsensitiveOption);

    const QStringList lines = out.split('\n');
    bool inTargetBlock = false;
    for (const QString &raw : lines) {
        const QString line = raw.trimmed();
        if (line.startsWith(QStringLiteral("process name ["))) {
            inTargetBlock = line.contains(QLatin1Char('[') + bundle + QLatin1Char(']'),
                                          Qt::CaseInsensitive);
            continue;
        }
        if (!inTargetBlock)
            continue;

        const QRegularExpressionMatch m = pidRe.match(line);
        if (m.hasMatch()) {
            bool ok = false;
            const qint64 v = m.captured(1).toLongLong(&ok);
            if (ok && v > 0)
                return v;
        }
    }
    return -1;
}

static bool lineContainsPidAndBundle(const QString &line, qint64 pid, const QString &bundle)
{
    if (pid <= 0 || bundle.isEmpty())
        return false;
    if (!line.contains(bundle, Qt::CaseInsensitive))
        return false;
    const QStringList tok = line.simplified().split(' ', Qt::SkipEmptyParts);
    for (const QString &t : tok) {
        bool ok = false;
        if (t.toLongLong(&ok) == pid && ok)
            return true;
    }
    return false;
}
} // namespace

qint64 harmonyQueryApplicationPid(const FilePath &hdc,
                                  const QString &serialNumber,
                                  const QString &bundleName,
                                  QString *sourceOut)
{
    if (bundleName.isEmpty())
        return -1;
    auto hit = [sourceOut](qint64 pid, const QString &source) {
        if (pid > 0 && sourceOut)
            *sourceOut = source;
        return pid;
    };

    // Prefer direct runtime pid lookup first when available.
    const QString pidofOut = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("pidof"), bundleName});
    const QList<qint64> pidofPids = parsePidListFromPidof(pidofOut);
    if (!pidofPids.isEmpty()) {
        const QString psA = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("ps"), QStringLiteral("-A")});
        if (qint64 pid = pickBestPidFromPsForBundle(psA, bundleName, pidofPids); pid > 0)
            return hit(pid, QStringLiteral("pidof+ps"));
        // pidof typically returns main process first; keep that as fallback.
        return hit(pidofPids.constFirst(), QStringLiteral("pidof"));
    }

    // Prefer process-runtime view from ability manager.
    const QString aaProcOut
        = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("aa"), QStringLiteral("dump"),
                                                QStringLiteral("-r")});
    if (qint64 pid = parsePidFromAaProcessDump(aaProcOut, bundleName); pid > 0) {
        return hit(pid, QStringLiteral("aa dump -r"));
    }

    const QString bmOut = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("bm"), QStringLiteral("dump"),
                                                                 QStringLiteral("-n"), bundleName});
    if (qint64 pid = parsePidFromKeyValueDump(bmOut); pid > 0) {
        return hit(pid, QStringLiteral("bm dump -n"));
    }

    const QString aaOut = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("aa"), QStringLiteral("dump"),
                                                                QStringLiteral("-b"), bundleName});
    if (qint64 pid = parsePidFromKeyValueDump(aaOut); pid > 0) {
        return hit(pid, QStringLiteral("aa dump -b"));
    }

    QString psOut = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("ps"), QStringLiteral("-A")});
    if (qint64 pid = parsePidFromPs(psOut, bundleName); pid > 0) {
        return hit(pid, QStringLiteral("ps -A"));
    }

    psOut = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("ps"), QStringLiteral("-ef")});
    if (qint64 pid = parsePidFromPs(psOut, bundleName); pid > 0)
        return hit(pid, QStringLiteral("ps -ef"));
    return -1;
}

bool harmonyPidLooksLikeBundleProcess(const FilePath &hdc,
                                      const QString &serialNumber,
                                      const QString &bundleName,
                                      qint64 pid)
{
    if (pid <= 0 || bundleName.isEmpty())
        return false;
    const QString psA = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("ps"), QStringLiteral("-A")});
    const QStringList aLines = psA.split('\n', Qt::SkipEmptyParts);
    for (const QString &line : aLines) {
        if (lineContainsPidAndBundle(line, pid, bundleName))
            return true;
    }
    const QString psEf = runHdcShellOutput(hdc, serialNumber, {QStringLiteral("ps"), QStringLiteral("-ef")});
    const QStringList efLines = psEf.split('\n', Qt::SkipEmptyParts);
    for (const QString &line : efLines) {
        if (lineContainsPidAndBundle(line, pid, bundleName))
            return true;
    }
    return false;
}

static const ProjectNode *currentProjectNode(const BuildConfiguration *bc)
{
    return bc->project()->findNodeForBuildKey(bc->activeBuildKey());
}

QString packageName(const ProjectExplorer::BuildConfiguration *bc)
{
    QString packageName;
    const FilePath harmonyBuildDir = harmonyBuildDirectory(bc);
    const Result<QByteArray> appJsonContents = harmonyBuildDir.pathAppended("AppScope/app.json5")
                                                  .fileContents();
    if (appJsonContents) {
        QJsonObject rootJson = QJsonDocument::fromJson(*appJsonContents).object();
        auto appObject = rootJson.value("app").toObject();
        packageName = appObject.value("bundleName").toString();
    }
    return packageName;
}

static QString abilityFromModuleJsonObject(const QJsonObject &moduleObject)
{
    const QJsonArray abilities = moduleObject.value(QStringLiteral("abilities")).toArray();
    if (abilities.isEmpty())
        return {};

    QString firstName;
    QString exportedName;
    for (const QJsonValue &v : abilities) {
        const QJsonObject ab = v.toObject();
        const QString n = ab.value(QStringLiteral("name")).toString();
        if (n.isEmpty())
            continue;
        if (firstName.isEmpty())
            firstName = n;
        if (ab.value(QStringLiteral("exported")).toBool())
            exportedName = n;
    }
    if (!exportedName.isEmpty())
        return exportedName;
    return firstName;
}

static void collectAbilityFromModuleJson5(const FilePath &jsonPath,
                                          QString *entryAbility,
                                          QString *anyAbility)
{
    if (!jsonPath.isReadableFile())
        return;

    const Result<QByteArray> raw = jsonPath.fileContents();
    if (!raw)
        return;

    QJsonParseError err{};
    const QJsonDocument doc = QJsonDocument::fromJson(*raw, &err);
    if (err.error != QJsonParseError::NoError || !doc.isObject())
        return;

    const QJsonObject moduleObject = doc.object().value(QStringLiteral("module")).toObject();
    if (moduleObject.isEmpty())
        return;

    const QString ability = abilityFromModuleJsonObject(moduleObject);
    if (ability.isEmpty())
        return;

    if (moduleObject.value(QStringLiteral("type")).toString() == QStringLiteral("entry")) {
        if (entryAbility->isEmpty())
            *entryAbility = ability;
    } else if (anyAbility->isEmpty()) {
        *anyAbility = ability;
    }
}

QString defaultHarmonyAbilityName(const BuildConfiguration *bc)
{
    const FilePath root = harmonyBuildDirectory(bc);
    if (root.isEmpty() || !root.isReadableDir())
        return {};

    QString entryAbility;
    QString anyAbility;

    collectAbilityFromModuleJson5(root.pathAppended(QStringLiteral("entry/src/main/module.json5")),
                                &entryAbility,
                                &anyAbility);

    if (root.isReadableDir()) {
        const FilePaths children = root.dirEntries(QDir::Dirs | QDir::NoDotAndDotDot);
        for (const FilePath &ch : children) {
            const QString name = ch.fileName();
            if (name == QStringLiteral("AppScope") || name == QStringLiteral("hvigor")
                || name == QStringLiteral("oh_modules") || name.startsWith(QLatin1Char('.')))
                continue;
            collectAbilityFromModuleJson5(ch.pathAppended(QStringLiteral("src/main/module.json5")),
                                        &entryAbility,
                                        &anyAbility);
        }
    }

    if (!entryAbility.isEmpty())
        return entryAbility;
    return anyAbility;
}

Utils::FilePath harmonyBuildDirectory(const ProjectExplorer::BuildConfiguration *bc)
{
    QString suffix;
    const ProjectExplorer::Project *project = bc->project();
    if (project->extraData(Ohos::Constants::HarmonyBuildTargetDirSupport).toBool()
        && project->extraData(Ohos::Constants::UseHarmonyBuildTargetDir).toBool())
        suffix = QString("-%1").arg(bc->activeBuildKey());

    return buildDirectory(bc) / (Constants::HARMONY_BUILD_DIRECTORY + suffix);
}

Utils::FilePath buildDirectory(const ProjectExplorer::BuildConfiguration *bc)
{
    const QString buildKey = bc->activeBuildKey();

    // Get the target build dir based on the settings file path
    FilePath buildDir;
    const ProjectNode *node = bc->project()->findNodeForBuildKey(buildKey);
    if (node) {
        const QString settingsFile = node->data(Constants::HarmonyDeploySettingsFile).toString();
        buildDir = FilePath::fromUserInput(settingsFile).parentDir();
    }

    if (!buildDir.isEmpty())
        return buildDir;

    // Otherwise fallback to target working dir
    buildDir = bc->buildDirectory();
    return buildDir;
}

QString buildKeyForCMakeExtraData(const BuildConfiguration *bc)
{
    if (!bc)
        return {};
    const QString buildKey = bc->activeBuildKey();
    if (buildKey != QString::fromLatin1(Constants::HARMONY_DEFAULT_RUN_BUILD_KEY))
        return buildKey;
    const BuildSystem *bs = bc->buildSystem();
    const Project *proj = bc->project();
    if (!bs || !proj)
        return buildKey;
    for (const BuildTargetInfo &ti : bs->applicationTargets()) {
        if (ti.buildKey.isEmpty())
            continue;
        if (proj->findNodeForBuildKey(ti.buildKey))
            return ti.buildKey;
    }
    return buildKey;
}

bool isQt5CmakeProject(const ProjectExplorer::Target *target)
{
    const QtSupport::QtVersion *qt = QtSupport::QtKitAspect::qtVersion(target->kit());
    const bool isQt5 = qt && qt->qtVersion() < QVersionNumber(6, 0, 0);
    const Core::Context cmakeCtx(CMakeProjectManager::Constants::CMAKE_PROJECT_ID);
    const bool isCmakeProject = (target->project()->projectContext() == cmakeCtx);
    return isQt5 && isCmakeProject;
}

QString deviceSerialNumber(const ProjectExplorer::BuildConfiguration *bc)
{
    return bc->extraData(HarmonyDeviceSn).toString();
}

void setDeviceSerialNumber(ProjectExplorer::BuildConfiguration *bc, const QString &deviceSerialNumber)
{
    qCDebug(harmonyDeviceLog) << "Target device serial changed:"
                               << bc->target()->displayName() << deviceSerialNumber;
    bc->setExtraData(HarmonyDeviceSn, deviceSerialNumber);
}
static QString preferredAbi(const QStringList &appAbis, const BuildConfiguration *bc)
{
    const auto deviceAbis = bc->extraData(HarmonyDeviceAbis).toStringList();

    return Utils::findOrDefault(deviceAbis,[appAbis](const auto &abi) { return appAbis.contains(abi); });
}
QString hapDevicePreferredAbi(const ProjectExplorer::BuildConfiguration *bc)
{
    const FilePath libsPath = harmonyBuildDirectory(bc).pathAppended("entry/libs");
    if (!libsPath.exists()) {
        if (const ProjectNode *node = currentProjectNode(bc)) {
            const QString abi = preferredAbi(
                node->data(Ohos::Constants::HarmonyAbis).toStringList(), bc);
            if (abi.isEmpty())
                return node->data(Ohos::Constants::OHOS_ARCH).toString();
        }
    }
    QStringList apkAbis;
    const FilePaths libsPaths = libsPath.dirEntries(QDir::Dirs | QDir::NoDotAndDotDot);
    for (const FilePath &abiDir : libsPaths) {
        if (!abiDir.dirEntries({{"*.so"}, QDir::Files | QDir::NoDotAndDotDot}).isEmpty())
            apkAbis << abiDir.fileName();
    }
    return preferredAbi(apkAbis, bc);
}

QString harmonyDebuggerPreferredAbi(const BuildConfiguration *bc)
{
    if (!bc)
        return {};

    QString abi = hapDevicePreferredAbi(bc).trimmed();
    if (!abi.isEmpty())
        return abi;

    if (const BuildSystem *bs = bc->buildSystem()) {
        abi = bs->extraData(buildKeyForCMakeExtraData(bc), Constants::OHOS_ARCH).toString().trimmed();
        if (!abi.isEmpty())
            return abi;
    }

    if (Target *target = bc->target()) {
        if (Kit *kit = target->kit()) {
            const QStringList kitAbis = applicationAbis(kit);
            for (const QString &a : kitAbis) {
                const QString t = HarmonyConfig::ohosLldbTripleForAbi(a.trimmed());
                if (!t.isEmpty())
                    return a.trimmed();
            }
        }
    }

    const QStringList devAbis = bc->extraData(HarmonyDeviceAbis).toStringList();
    for (const QString &a : devAbis) {
        const QString t = HarmonyConfig::ohosLldbTripleForAbi(a.trimmed());
        if (!t.isEmpty())
            return a.trimmed();
    }
    if (!devAbis.isEmpty())
        return devAbis.first().trimmed();

    return {};
}

void setDeviceAbis(ProjectExplorer::BuildConfiguration *bc, const QStringList &deviceAbis)
{
    bc->setExtraData(HarmonyDeviceAbis, deviceAbis);
}

int deviceApiLevel(const ProjectExplorer::BuildConfiguration *bc)
{
    return bc->extraData(ApiLevelKey).toInt();
}

void setDeviceApiLevel(ProjectExplorer::BuildConfiguration *bc, int level)
{
    qCDebug(harmonyDeviceLog) << "Target device API level changed:"
                               << bc->target()->displayName() << level;
    bc->setExtraData(ApiLevelKey, level);
}

FilePath appJson5Path(const ProjectExplorer::BuildConfiguration *bc)
{
    QVariant manifest = bc->extraData(HarmonyAppJson5Name);
    if (manifest.isValid())
        return manifest.value<FilePath>();
    return harmonyBuildDirectory(bc).pathAppended(HarmonyAppJson5Name);
}

void setAppJson5Path(ProjectExplorer::BuildConfiguration *bc, const Utils::FilePath &path)
{
    bc->setExtraData(HarmonyAppJson5Name, QVariant::fromValue(path));
}
static int parseMinSdk(const FilePath &appJson5Path)
{
    const Result<QByteArray> appJsonContents = appJson5Path.fileContents();
    if (!appJsonContents) {
        qCWarning(harmonyDeployLog) << "Failed to read" << appJson5Path;
        return 0;
    }
    QJsonObject rootJson = QJsonDocument::fromJson(*appJsonContents).object();
    auto productsArray = rootJson.value("products").toArray();
    int minSdkVersion = OhProjecteCreator::latestApiLevel();
    for (const auto &productValue : std::as_const(productsArray)) {
        auto productObject = productValue.toObject();
        QString compatibleSdkVersion = productObject.value("compatibleSdkVersion").toString();
        minSdkVersion = qMin(minSdkVersion, OhProjecteCreator::apiLevelForVersion(compatibleSdkVersion));
    }
    return minSdkVersion;
}

int minimumSDK(const ProjectExplorer::BuildConfiguration *bc)
{
    const auto buildProfile = harmonyBuildDirectory(bc).pathAppended("build-profile.json5");
    if (!buildProfile.exists())
        return minimumSDK(bc->kit());

    const int minSdkVersion = parseMinSdk(buildProfile);
    if (minSdkVersion == 0)
        return defaultMinimumSDK(QtSupport::QtKitAspect::qtVersion(bc->kit()));
    return minSdkVersion;
}

int minimumSDK(const ProjectExplorer::Kit *kit)
{
    int minSdkVersion = -1;
    QtSupport::QtVersion *version = QtSupport::QtKitAspect::qtVersion(kit);
    if (version && version->targetDeviceTypes().contains(Constants::HARMONY_DEVICE_TYPE)) {
        auto harmonyQt = dynamic_cast<const HarmonyQtVersion *>(version);

        if (harmonyQt)
            minSdkVersion = harmonyQt->supportOhVersion().majorVersion();
    }
    if (minSdkVersion == 0)
        return defaultMinimumSDK(version);
    return minSdkVersion;
}

int defaultMinimumSDK(const QtSupport::QtVersion *qtVersion)
{
    auto harmonyQt = dynamic_cast<const HarmonyQtVersion *>(qtVersion);
    if (harmonyQt)
        return harmonyQt->supportOhVersion().majorVersion();
    return OhProjecteCreator::defaultApiLevel();
}

namespace {

const QString kOutputsRelative = QStringLiteral("build/default/outputs/default");

FilePath moduleRootFromBuildProfileEntry(const FilePath &ohProRoot, const QJsonObject &moduleObject)
{
    const QString srcPath = moduleObject.value(QStringLiteral("srcPath")).toString().trimmed();
    if (!srcPath.isEmpty())
        return ohProRoot.resolvePath(srcPath);
    const QString name = moduleObject.value(QStringLiteral("name")).toString();
    if (!name.isEmpty())
        return ohProRoot.pathAppended(name);
    return {};
}

FilePath pickHapInOutputDir(const FilePath &outputDir, const QString &moduleName)
{
    if (!outputDir.isReadableDir())
        return {};

    const QStringList exactCandidates{
        moduleName + QStringLiteral("-default-signed.hap"),
        moduleName + QStringLiteral("-default-debug-signed.hap"),
        moduleName + QStringLiteral("-signed.hap"),
    };
    for (const QString &fn : exactCandidates) {
        const FilePath p = outputDir.pathAppended(fn);
        if (p.isReadableFile())
            return p;
    }

    FilePaths haps = outputDir.dirEntries({{QStringLiteral("*.hap")}, QDir::Files});
    if (haps.isEmpty())
        return {};
    std::sort(haps.begin(), haps.end(), [](const FilePath &a, const FilePath &b) {
        return a.lastModified() > b.lastModified();
    });
    return haps.front();
}

FilePath resolveFromBuildProfileModules(const FilePath &ohProRoot, QStringList *diagnostic)
{
    const FilePath profilePath = ohProRoot.pathAppended(QStringLiteral("build-profile.json5"));
    if (!profilePath.isReadableFile()) {
        if (diagnostic)
            diagnostic->append(QStringLiteral("No readable build-profile.json5 — using entry + scan fallbacks."));
        return {};
    }

    const Result<QByteArray> content = profilePath.fileContents();
    if (!content) {
        if (diagnostic)
            diagnostic->append(QStringLiteral("Could not read build-profile.json5."));
        return {};
    }

    QJsonParseError parseError{};
    const QJsonDocument doc = QJsonDocument::fromJson(*content, &parseError);
    if (parseError.error != QJsonParseError::NoError || !doc.isObject()) {
        if (diagnostic) {
            diagnostic->append(QStringLiteral("build-profile.json5: JSON error: %1")
                                   .arg(parseError.errorString()));
        }
        return {};
    }

    const QJsonArray modules = doc.object().value(QStringLiteral("modules")).toArray();
    if (modules.isEmpty()) {
        if (diagnostic)
            diagnostic->append(QStringLiteral("build-profile.json5: empty modules[] — using entry fallbacks."));
        return {};
    }

    const auto tryOneModule = [&](const QJsonObject &mo, const QString &phase) -> FilePath {
        const QString moduleName = mo.value(QStringLiteral("name")).toString();
        const FilePath modRoot = moduleRootFromBuildProfileEntry(ohProRoot, mo);
        if (moduleName.isEmpty() || modRoot.isEmpty()) {
            if (diagnostic)
                diagnostic->append(QStringLiteral("[%1] skip (missing module name or path).").arg(phase));
            return {};
        }
        const FilePath outputDir = modRoot.pathAppended(kOutputsRelative);
        if (diagnostic) {
            diagnostic->append(
                QStringLiteral("[%1] module \"%2\" → %3").arg(phase, moduleName, outputDir.toUserOutput()));
        }
        return pickHapInOutputDir(outputDir, moduleName);
    };

    for (const QJsonValue &mv : modules) {
        const QJsonObject mo = mv.toObject();
        if (mo.value(QStringLiteral("type")).toString() != QStringLiteral("entry"))
            continue;
        const FilePath found = tryOneModule(mo, QStringLiteral("entry-type"));
        if (!found.isEmpty())
            return found;
    }

    for (const QJsonValue &mv : modules) {
        const QJsonObject mo = mv.toObject();
        if (mo.value(QStringLiteral("type")).toString() == QStringLiteral("entry"))
            continue;
        const FilePath found = tryOneModule(mo, QStringLiteral("other-module"));
        if (!found.isEmpty())
            return found;
    }

    return {};
}

FilePath legacyEntryHap(const FilePath &ohProRoot, QStringList *diagnostic)
{
    const FilePath defaultPath = ohProRoot.pathAppended(
        QStringLiteral("entry/build/default/outputs/default/entry-default-signed.hap"));
    if (diagnostic)
        diagnostic->append(QStringLiteral("Legacy path: %1").arg(defaultPath.toUserOutput()));
    if (defaultPath.isReadableFile())
        return defaultPath;

    const FilePath outputDir = ohProRoot.pathAppended(QStringLiteral("entry/build/default/outputs/default"));
    return pickHapInOutputDir(outputDir, QStringLiteral("entry"));
}

FilePath newestHapRecursive(const FilePath &ohProRoot, QStringList *diagnostic)
{
    QDirIterator it(ohProRoot.toUserOutput(),
                    {QStringLiteral("*.hap")},
                    QDir::Files,
                    QDirIterator::Subdirectories);
    FilePath best;
    QDateTime bestTime;
    int n = 0;
    while (it.hasNext()) {
        const FilePath candidate = FilePath::fromString(it.next());
        if (!candidate.isReadableFile())
            continue;
        ++n;
        const QDateTime t = candidate.lastModified();
        if (!bestTime.isValid() || t > bestTime) {
            bestTime = t;
            best = candidate;
        }
    }
    if (diagnostic) {
        diagnostic->append(QStringLiteral("Recursive *.hap: %1 file(s); newest: %2")
                                 .arg(QString::number(n),
                                      best.isEmpty() ? QStringLiteral("(none)") : best.toUserOutput()));
    }
    return best;
}

} // namespace

FilePath findBuiltHapPackage(const FilePath &ohProRoot, QString *diagnosticOut)
{
    if (!ohProRoot.isReadableDir()) {
        if (diagnosticOut)
            *diagnosticOut = QStringLiteral("Not a readable directory: ") + ohProRoot.toUserOutput();
        return {};
    }

    QStringList lines;
    FilePath found = resolveFromBuildProfileModules(ohProRoot, &lines);
    if (found.isEmpty())
        found = legacyEntryHap(ohProRoot, &lines);
    if (found.isEmpty())
        found = newestHapRecursive(ohProRoot, &lines);

    if (diagnosticOut)
        *diagnosticOut = lines.join(QLatin1Char('\n'));

    return found;
}

static QString runHdcShellCommand(const QString &deviceSerial, const QString &shellOneLiner,
                                  bool *ok = nullptr)
{
    const FilePath hdc = HarmonyConfig::hdcToolPath();
    if (!hdc.isExecutableFile()) {
        if (ok)
            *ok = false;
        return {};
    }
    QStringList args;
    if (!deviceSerial.trimmed().isEmpty())
        args.append(hdcSelector(deviceSerial));
    args << QStringLiteral("shell") << shellOneLiner;

    Process process;
    process.setCommand(CommandLine{hdc, args});
    process.setWorkingDirectory(hdc.parentDir());
    process.runBlocking(std::chrono::seconds(30));
    const bool success = process.result() == ProcessResult::FinishedWithSuccess;
    if (ok)
        *ok = success;
    return process.allOutput();
}

static HarmonyShellUidClass parseIdOutput(const QString &raw)
{
    static const QRegularExpression re(QStringLiteral(R"(\buid=(\d+))"));
    const QRegularExpressionMatch m = re.match(raw);
    if (!m.hasMatch())
        return HarmonyShellUidClass::Unknown;
    bool convOk = false;
    const qulonglong uid = m.captured(1).toULongLong(&convOk);
    if (!convOk)
        return HarmonyShellUidClass::Unknown;
    return uid == 0 ? HarmonyShellUidClass::Root : HarmonyShellUidClass::NonRoot;
}

static HarmonySelinuxState parseGetenforceOutput(const QString &raw)
{
    const QString t = raw.trimmed().toLower();
    if (t.isEmpty())
        return HarmonySelinuxState::Unknown;
    if (t == QLatin1String("enforcing"))
        return HarmonySelinuxState::Enforcing;
    if (t == QLatin1String("permissive"))
        return HarmonySelinuxState::Permissive;
    if (t == QLatin1String("disabled"))
        return HarmonySelinuxState::Disabled;
    return HarmonySelinuxState::Unknown;
}

HarmonyNativeDebugShellProbe probeNativeDebugShellEnvironment(const QString &deviceSerial)
{
    HarmonyNativeDebugShellProbe out;
    const FilePath hdc = HarmonyConfig::hdcToolPath();
    if (!hdc.isExecutableFile()) {
        out.hdcMissing = true;
        qCDebug(harmonyDeviceLog) << "probeNativeDebugShellEnvironment: hdc not executable";
        return out;
    }

    bool idOk = false;
    out.idOutput = runHdcShellCommand(deviceSerial, QStringLiteral("id"), &idOk);
    out.idCommandOk = idOk;
    out.uidClass = parseIdOutput(out.idOutput);
    if (!idOk)
        qCDebug(harmonyDeviceLog) << "probeNativeDebugShellEnvironment: id failed" << out.idOutput;

    bool geOk = false;
    out.getenforceOutput = runHdcShellCommand(deviceSerial, QStringLiteral("getenforce"), &geOk);
    out.getenforceCommandOk = geOk;
    out.selinux = parseGetenforceOutput(out.getenforceOutput);
    if (!geOk)
        qCDebug(harmonyDeviceLog) << "probeNativeDebugShellEnvironment: getenforce failed"
                                  << out.getenforceOutput;

    return out;
}

HarmonyNativeDebugRecipeKind nativeDebugRecipeKind(const HarmonyNativeDebugShellProbe &probe)
{
    if (probe.uidClass == HarmonyShellUidClass::Unknown)
        return HarmonyNativeDebugRecipeKind::Unknown;
    if (probe.uidClass == HarmonyShellUidClass::NonRoot)
        return HarmonyNativeDebugRecipeKind::FavorUserHapAbstractSocket;
    return HarmonyNativeDebugRecipeKind::FavorRootTcpListening;
}

}
